### ISSUE TITLE
Please provide an example of usage

### ISSUE THREAD

**Issue by conorthedeveloper** [TrollSkull/BashTube#1]
I was wondering if you could provide an example of how to download a youtube video?

On the prompt screen, I type in 'video' followed by the URL of the video, but it says 'command not found'.

e.g. typing the following and pressing enter gives 'command not found'

BashTube >> video https://www.youtube.com/watch?v=DybzmWASPkE

**Comment by TrollSkull** [comment]
Of course, I plan to create a video about the use of this script, I will get to work with that, I will put it in the README.md

When I finish the video and upload it I will comment with the link of the video :D

To download a video you have to write the option "video", then you will be asked to paste the link of the video you want to download (To get the link you have to go to YouTube and enter the video, there it will appear to share and copy the link)

------------Example------------

BashTube >> video

(and then this will appear for you to paste the link)

Copy & Paste the URL of the video: (paste the link)


and the video will begin to download (The downloaded video will be stored in the "Downloads" folder)

I hope this explanation has been helpful

**Comment by conorthedeveloper** [comment]
Yes, I followed your instructions, but after typing in 'video' and pressing enter an error message briefly appeared:

_File "video.py", line 2 in <module>
 import youtube_dl
 ImportError: No module named youtube_dl_

So, I pip installed youtube_dl. Having installed youtube_dl, the error message listed above has now gone, but the expected behaviour still doesn't happen(it doesn't prompt me for a video url as suggested in your post above). 

So now, if I type 'video', press Enter, then the prompt returns to BashTube >>

(I'm on a Mac btw)

**Comment by TrollSkull** [comment]
So strange, for the moment it has not happened to me, I will try to investigate what has caused that error
